### ISSUE TITLE
Could you please add an example how to use 3b-ps-asdf?

### ISSUE THREAD

**Issue by svetlyak40wt** [3b/3b-ps-asdf#1]

**Comment by 3b** [comment]
Might take me a while, since I have limited coding time at the moment and haven't even looked at the code in years.

I think https://github.com/3b/ps-webgl/blob/master/ps-webgl.asd and https://github.com/3b/slime-proxy/blob/master/slimy.ui.asd show how it was intended to work. If I remember correctly, loading the `.asd` file would create a `.js` file for each `:3b-ps-file` component.

**Comment by svetlyak40wt** [comment]
Thank you, will try this way.
